In [3]:
import torch

embedding = torch.nn.Embedding(
    num_embeddings=5,
    embedding_dim=3
)

print("Embedding Matrix:")
print(embedding.weight)

tokens = torch.tensor([0, 2, 4])

vectors = embedding(tokens)

print("\nToken IDs:")
print(tokens)

print("\nEmbedding Vectors:")
print(vectors)

print("\nOutput Shape:")
print(vectors.shape)

Embedding Matrix:
Parameter containing:
tensor([[ 2.0908,  0.2278,  0.3186],
        [ 1.5035,  0.9105, -0.1139],
        [-1.5209,  0.6832, -0.2867],
        [-1.0378, -1.0627, -0.1708],
        [ 0.7957, -1.9345, -0.4437]], requires_grad=True)

Token IDs:
tensor([0, 2, 4])

Embedding Vectors:
tensor([[ 2.0908,  0.2278,  0.3186],
        [-1.5209,  0.6832, -0.2867],
        [ 0.7957, -1.9345, -0.4437]], grad_fn=<EmbeddingBackward0>)

Output Shape:
torch.Size([3, 3])
